# Generated by Django 5.0.1 on 2024-01-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='addres',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='descriptions',
        ),
    ]
